name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: windows-latest
    steps:
      - name: good morning
        run: echo "Hai"
      - name: good evening
        run: echo "Hello"
